Parameters:
  EnvironmentName:
    Type: String
    Default: MinecraftServer

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/26
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
